### ISSUE TITLE
how to use it in an axios interceptor

### ISSUE THREAD

**Issue by l0rraine** [behawesometw/vue-hawesome-modal#7]
I'm a newbie for Vue. And I want to make an uniform error handler and toast user something. But the this.$h throw the error "Cannot read property 'dialog' of undefined". So how can I use this plugin in a standalone js file?

Really really need your help, thx.

**Comment by behawesometw** [comment]
First, make sure `this` points to the Vue instance.

I recommend using CommonJS module to install vue-hawesome-modal.
